version: '3.3'

services:
  postgres: 
    image: postgres:16-alpine
    container_name: pg_container
    restart: unless-stopped
    ports:
     - "5432:5432"
    environment:
      TZ: Canada/Eastern
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: WIMTACH_ExcerciseDB

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: pgadmin4_container
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  
